module.exports = {
  endpoints: {
    // "br": "br1",
    // "eune": "eun1",
    // "euw": "euw1",
    // "jp": "jp1",
    // "kr": "kr",
    // "lan": "la1",
    // "las": "la2",
    "na": "na1",
    // "oce": "oc1",
    // "tr": "tr1",
    // "ru": "ru",
    // "pbe": "pbe1"
  },
  languages: {
    "English": "en_US",
    "Chinese": "zh_CN",
    "Korean": "ko_KR",
    "Japanese": "ja_JP",
    "Spanish": "es_ES",
    "Vietnamese": "vn_VN",
    "Thailand": "th_TH",
    "Turkish": "tr_TR",
    "Russian": "ru_RU",
    "Portuguese": "pt_BR",
    "French": "fr_FR",
    "Italian": "it_IT",
    "German": "de_DE",
    "Hungary": "hu_HU",
    "Romanian": "ro_RO",
    "Polish": "pl_PL",
    "Greek": "el_GR",
    "Czech": "cs_CZ"
  },
  season: 13,
  key: "RGAPI-f56e42ef-0c34-4b99-97c9-b0d2fe42f4e6",
  ver: "9.13.1",
  secondRate: 500,
  minuteRate: 30000
}